###############################################################
# Official triggerFS configuration toml skeleton file         #
# In case you are missing the core plugins:                   #
# you can find them at https://github.com/triggerfsio/plugins #
###############################################################

### MAIN SECTION
[main]
# team name for login
team = "myawesometeam"
# identity (email address) for login
identity = "demo@example.com"
# password for login
secret = "secret"
# or provide an api JWT to skip above login credentials
# jwt = ""
### MAIN SECTION END


### FS SECTION
[triggerfs]
# mountpoint path
mountpoint = "/home/user/mountpoint"
# logfile for logging of fs module
logfile = "/home/user/triggerfs.log"
### FS SECTION END


### CLIENT SECTION
[triggerfs-client]
# logfile for logging of client module
logfile = "/home/user/triggerfs_client.log"
### CLIENT SECTION END


### WORKERS SECTION
[workers]
# path to plugins folder (must be absolute path).
pluginspath = "/home/user/gocode/src/github.com/triggerfsio/plugins/plugins"

# subsections of [workers] section identified by identities prefixed with "workers."
#[workers.worker01]
#token = "c3644eda-..."
#[workers.worker02]
#token = "c366e0e6-..."
#[workers.worker03]
#token = "c368b308-..."
### WORKERS SECTION END
